sudo: required
branches:
  only:
  - gh-pages
  - "/.*/"
services:
- docker
before_install:
- chmod +x ./ci_scripts/if_readme_only.sh
- "./ci_scripts/if_readme_only.sh"
script:
- docker image build -t pingidentity/pingdatacommon ./pingdatacommon
- docker-compose -f ./pingdirectory/build.test.yml up
- docker image build -t samirgandhi/pingfederate ./pingfederate
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push samirgandhi/pingfederate
notifications:
  slack: MiKkb3i+CvjR0pc5r3oNKipI9HDe552OLenqugzmHIlAHRQhDJXM8sR8ddLZORWzd9weI3l44be05/v1DPTHM1Z8m8bhdnZJg2x7GxlC823CySMVJywLrmNDGebZq/p0PucQ673pV1CDTUdlRmig5/6PunrnPrssNFYSHTgZ4OCh3wRHM+FsF9QhIOsWUNBdEheCaCABroqUvxlYjMa8elTpK8cybj/YnuzPnVgMUkhQjMnl4IbrPNbw/fL0f48vSX90Vcpg/mdaKsswaSYuySlkPae3b+se9UyG+z1QNcSJjlR+JUwc531/ZPUo6prBjmicEdGxee39Yi8ecKv75RUila/dWr3zQmu8XrlKNdqHiId/BFNeTKd6ZZqsq8dThV4QUMb1LiKor/CckIh/9ZLaW8bIB5HWyxN/CHsZDZK06dNxGCwEh/Q2N0RHgJbOHw7hW0j0PkOEJMmzldXe0zpWtn3RWj6go9gr2bIKd0kz4mWC3dkpvUYNKBKOTOYzK2vWMBGZDab2lsMAey7ooQCwjkGvFVnWBkuiGLRIUEQjjF82FUOdC51ZwvbZa2vcYSU5E7dFELEFAPByrUaDx4Y29fgC73mgZeRhD8mqOwl1504wn4inVE4H5qWqJsN0U/LpmMTd7m/lVCdsGMh690U+w6wjJHK4NWHQ65Plwaw=