version: "2"

services:
  sut:
    build: .
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingdirectory-basic.git
    command: wait-for pingdirectory:389 -t 180 -- /opt/tools/ldapsearch -h pingdirectory -b "" -s base '(&)' 1.1
