version: "2"

services:
  pingdirectory:
    build: .
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingdirectory-basic.git

  sut:
    image: pingidentity/ldap-sdk-tools
    command: wait-for pingdirectory:389 -t 180 -- /opt/tools/ldapsearch -h pingdirectory -b "" -s base '(&)' 1.1
    depends_on:
      - "pingdirectory"
